spring.application.name=am-gateway
server.port=8080

identity.service.url=${IDENTITY_SERVICE_URL:http://localhost:3001}
alert.service.url=${ALERT_SERVICE_URL:http://localhost:3002}
resource.service.url=${RESOURCE_SERVICE_URL:http://localhost:3003}
admin.service.url=${ADMIN_SERVICE_URL:http://localhost:3004}

cors.allowed-origins=${CORS_ORIGIN:*}
